
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php
      - dbpg

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - .:/app/

  dbpg:
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: dockerdb
    ports:
      - "5433:5432"
    volumes:
      - .:/app/
      - ./data:/var/lib/postgresql/data
